### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by daviel** [natdan/rpi-libgdx-example#1]
On a clean install of Raspbian on my RPi3b I have recognized the following things:

**1. When running ./gradlew desktop:run following error occured:**

```
./gradlew desktop:run
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/pi/Schreibtisch/rpi-libgdx-example/rpi-libgdx-example/build.gradle' line: 59

* What went wrong:
A problem occurred evaluating root project 'rpi-libgdx-example'.
> Failed to apply plugin [id 'android']
   > Minimum supported Gradle version is 3.3. Current version is 3.2. If using the gradle wrapper, try editing the distributionUrl in /home/pi/.gradle/daemon/3.2/gradle/wrapper/gradle-wrapper.properties to gradle-3.3-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 27.616 secs
```

--> I could fix that by setting the version in the gradle-wrapper.properties to version 3.3

**2. The desktop build.gradle has no valid main class name set so I had to change the following.**

.../rpi-libgdx-example/desktop/build.gradle:
**From:** project.ext.mainClassName = "com.mygdx.game.desktop.DesktopLauncher"
**To:** project.ext.mainClassName = "org.ah.libgdx.rpi.desktop.TestDesktopLauncher"
or alternatively:
**From:** project.ext.mainClassName = "com.mygdx.game.desktop.DesktopLauncher"
**To:** project.ext.mainClassName = "org.ah.libgdx.rpi.desktop.TestDesktopLauncherJogl"

**3. Trying to run both of the tests resulted in the following errors:**

TestDesktopLauncher:
```
./gradlew desktop:run
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:desktop:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning

:desktop:processResources UP-TO-DATE
:desktop:classes
:desktop:run
LwjglApplication: Couldn't initialize audio, disabling audio
java.lang.UnsatisfiedLinkError: /tmp/libgdxpi/1c78875b/liblwjgl.so: /tmp/libgdxpi/1c78875b/liblwjgl.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.openal.AL.<clinit>(AL.java:59)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.<init>(OpenALAudio.java:72)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:88)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:69)
	at org.ah.libgdx.rpi.desktop.TestDesktopLauncher.main(TestDesktopLauncher.java:13)
Exception in thread "LWJGL Application" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.Sys
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:591)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

BUILD SUCCESSFUL

Total time: 31.077 secs
```

TestDesktopLauncherJogl:

```
./gradlew desktop:run
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:desktop:compileJava UP-TO-DATE
:desktop:processResources UP-TO-DATE
:desktop:classes UP-TO-DATE
:desktop:runlibEGL warning: DRI2: failed to authenticate
Exception in thread "main" com.jogamp.opengl.GLException: Profile GLES2 is not available on EGLGraphicsDevice[type .egl, v1.4.0, connection decon, unitID 0, handle 0x61570140, owner true, NullToolkitLock[obj 0x8a9f61]], but: []
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1004)
	at com.badlogic.gdx.backends.jogamp.JoglGraphicsBase.initialize(JoglGraphicsBase.java:82)
	at com.badlogic.gdx.backends.jogamp.JoglNewtGraphics.<init>(JoglNewtGraphics.java:49)
	at com.badlogic.gdx.backends.jogamp.JoglNewtApplication.createGraphics(JoglNewtApplication.java:59)
	at com.badlogic.gdx.backends.jogamp.JoglNewtApplication.createGraphics(JoglNewtApplication.java:32)
	at com.badlogic.gdx.backends.jogamp.JoglApplicationBase.<init>(JoglApplicationBase.java:55)
	at com.badlogic.gdx.backends.jogamp.JoglNewtApplication.<init>(JoglNewtApplication.java:49)
	at org.ah.libgdx.rpi.desktop.TestDesktopLauncherJogl.main(TestDesktopLauncherJogl.java:14)


BUILD SUCCESSFUL

Total time: 11.242 secs
```

Is there currently a way to run this example? I am grateful for every help.

**Comment by natdan** [comment]
TestDesktopLauncher is for desktop/laptop (where lwjgl) works and TestDesktopLauncherJogl is for JOGL (that is supposed to work on RPi).

In the mean time - may I ask you to make a PR with your changes so I can incorporate them here... If it is too much hustle clone repo, do the changes and I'll pull them back...

Error you're getting in TestDesktopLauncherJogl is due to two supplied open GLES drivers on RPi. I must confess I don't know the **correct** solution but I know how to bodge it so it works 🙄 

```
$ l /opt/vc/lib/libbrcmGLESv2*
-rw-r--r-- 1 root root 105768 Jun 15 21:25 /opt/vc/lib/libbrcmGLESv2.so
```
is driver I use. So one in `/usr/lib/arm-linux-gnueabihf` I save and brutally replace with the one above:
```
$ l /usr/lib/arm-linux-gnueabihf/libGLES*
lrwxrwxrwx 1 root root     21 Aug  4  2017 /usr/lib/arm-linux-gnueabihf/libGLESv1_CM.so.1 -> libGLESv1_CM.so.1.1.0
-rw-r--r-- 1 root root  17704 Aug  4  2017 /usr/lib/arm-linux-gnueabihf/libGLESv1_CM.so.1.1.0
lrwxrwxrwx 1 root root     14 Jun 15 21:53 /usr/lib/arm-linux-gnueabihf/libGLESv2.so -> libGLESv2.so.2
lrwxrwxrwx 1 root root     18 Jun 23 17:56 /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2 -> libGLESv2.so.2.0.0
-rw-r--r-- 1 root root 105768 Jun 15 21:47 /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2.0.0
-rw-r--r-- 1 root root  38184 Aug  4  2017 /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2.0.0.disabled
lrwxrwxrwx 1 root root     27 Jun 23 15:15 /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2.disabled -> libGLESv2.so.2.0.0.disabled
```

You can see there that I have renamed `libGLESv2.so.2.0.0` to `libGLESv2.so.2.0.0.disabled` and carefully redirected existing links to 'new' (copy of `libbrcmGLESv2.so`) `libGLESv2.so.2.0.0`. Let me know if you need more help with it... Also, do let me know if it worked! :)

**Comment by natdan** [comment]
Maybe I need a little script to do that fudge automatically! 🙄

**Comment by daviel** [comment]
I will commit my changes as a pull request. I will try your suggestions. Thanks for the help!

**Comment by natdan** [comment]
BTW - do you know what's really interesting with RPi? You can setup little SPI display like this (https://www.ebay.co.uk/itm/2-8-TFT-LCD-Display-Touch-Panel-SPI-Serial-240-320-ILI9341-5V-3-3V-STM32-L50/232849348166?hash=item3636e71646:g:jRcAAOSw3GVbSkfV:rk:2:pf:1&frcectupt=true) and have Java LibGDX software working on it, too! :)

Or simpler version: https://www.ebay.co.uk/itm/3-5-480x320-LCD-Panel-Touch-Screen-Display-HDMI-Monitor-for-Raspberry-Pi/332692933981?_trkparms=aid%3D555017%26algo%3DPL.CASSINI%26ao%3D1%26asc%3D20151005190540%26meid%3D6715a4777b43480e961b3b46e162e5f3%26pid%3D100505%26rk%3D1%26rkt%3D1%26%26itm%3D332692933981&_trksid=p2045573.c100505.m3226

**Comment by daviel** [comment]
Okay, so I had to link the libraries as mentioned by you and also disable vc4-kms-v3d overlay in the /boot/config.txt to get it working.

It's really bad that it only works like this. It would be great to get it up and running on a clean Raspbian installation. :/

**Comment by natdan** [comment]
I agree. And problem is somewhere between Raspbian itself and JOGL (or JOGL used here).
Ideally we would have LWJGL libraries build for RPi and delivered with rest of binaries... 

BTW I am just curious - what are you doing with LibGDX and RPi? :)

**Comment by daviel** [comment]
When running the desktoplauncher it says the following:

```
wjglApplication: Couldn't initialize audio, disabling audio
java.lang.UnsatisfiedLinkError: /tmp/libgdxpi/1c78875b/liblwjgl.so: /tmp/libgdxpi/1c78875b/liblwjgl.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
```

Which is really weird as you can easily install liblwjgl.so through the repository of Raspbian. I did so and the library is located here:
**/usr/lib/jni/liblwjgl.so**

I don't know why it is copying the 32-bit x86 library to the temp(where does it come from)?


I am trying to port a libgdx based game(shattered pixel dungeon) to the raspberry pi. Are you using it to build some GUIs on the RPi?

**Comment by kalexmills** [comment]
In case anyone else ends up in this corner of the internet:
https://www.raspberrypi.org/forums/viewtopic.php?t=191857

**Comment by daviel** [comment]
> In case anyone else ends up in this corner of the internet:
> https://www.raspberrypi.org/forums/viewtopic.php?t=191857

Were you able to get it running?
